<?php
use ReleaseParser\SceneParser;
use PHPUnit\Framework\TestCase;

/**
 * Test class for SceneParser.
 * Generated by PHPUnit on 2014-10-15 at 19:46:05.
 */
class SceneParserTest extends TestCase
{
    /**
     * @var SceneParser[]
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object[0] = new SceneParser('Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO');
        $this->object[1] = new SceneParser('22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV');
        $this->object[2] = new SceneParser('The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders');
        $this->object[3] = new SceneParser('Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER');
        $this->object[4] = new SceneParser('Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD');
        $this->object[5] = new SceneParser('Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT');
        $this->object[6] = new SceneParser('Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT');
        $this->object[7] = new SceneParser('Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD');
        $this->object[8] = new SceneParser('The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD');
        $this->object[9] = new SceneParser('Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD');
        $this->object[10] = new SceneParser('The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT');
        $this->object[11] = new SceneParser('Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES');
        $this->object[12] = new SceneParser('Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE');
        $this->object[13] = new SceneParser('The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS');
        $this->object[14] = new SceneParser('Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS');
        $this->object[15] = new SceneParser('Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot'); /* 3D kann vor und nach dem Jahr stehen */
        $this->object[16] = new SceneParser('Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE'); /* HSBS = Half Side-by-Side */
        $this->object[17] = new SceneParser('Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS');
        $this->object[18] = new SceneParser('Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE'); /* HOU = Half Over-Unter */
        $this->object[19] = new SceneParser('Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON');
        $this->object[20] = new SceneParser('Shortland.Street.S23E180.720p.HDTV.x264-FiHTV');
        $this->object[21] = new SceneParser('Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV');
        $this->object[22] = new SceneParser('Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW');
        $this->object[23] = new SceneParser('Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP');
        $this->object[24] = new SceneParser('No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV');
        $this->object[26] = new SceneParser('2012.AC3.720p.BluRay.x264-XXL');
        $this->object[27] = new SceneParser('Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER');
        $this->object[28] = new SceneParser('Noah.German.2014.LD.1080p.BluRay.x264-HCS');

        /*
        $this->assertEquals('', $this->object[0]->getResolution()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals('', $this->object[1]->getResolution()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals('', $this->object[2]->getResolution()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals('', $this->object[3]->getResolution()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals('', $this->object[4]->getResolution()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals('', $this->object[5]->getResolution()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('', $this->object[6]->getResolution()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('', $this->object[7]->getResolution()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals('', $this->object[8]->getResolution()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals('', $this->object[9]->getResolution()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals('', $this->object[10]->getResolution()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals('', $this->object[11]->getResolution()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals('', $this->object[12]->getResolution()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals('', $this->object[13]->getResolution()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('', $this->object[14]->getResolution()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('', $this->object[15]->getResolution()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals('', $this->object[16]->getResolution()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('', $this->object[17]->getResolution()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals('', $this->object[18]->getResolution()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('', $this->object[19]->getResolution()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals('', $this->object[20]->getResolution()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals('', $this->object[21]->getResolution()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals('', $this->object[22]->getResolution()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals('', $this->object[23]->getResolution()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals('', $this->object[24]->getResolution()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals('', $this->object[26]->getResolution()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals('', $this->object[27]->getResolution()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals('', $this->object[28]->getResolution()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
        */


    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    public function testGetType()
    {
    	$this->assertEquals('movie', $this->object[0]->getType());
    	$this->assertEquals('movie', $this->object[1]->getType());
    	$this->assertEquals('movie', $this->object[2]->getType());
    	$this->assertEquals('movie', $this->object[3]->getType());
    	$this->assertEquals('movie', $this->object[4]->getType());
    	$this->assertEquals('movie', $this->object[5]->getType());
    	$this->assertEquals('movie', $this->object[6]->getType());
    	$this->assertEquals('movie', $this->object[7]->getType());
    	$this->assertEquals('movie', $this->object[8]->getType());
    	$this->assertEquals('movie', $this->object[9]->getType());
    	$this->assertEquals('movie', $this->object[10]->getType());
    	$this->assertEquals('movie', $this->object[11]->getType());
    	$this->assertEquals('movie', $this->object[12]->getType());
    	$this->assertEquals('movie', $this->object[13]->getType());
    	$this->assertEquals('movie', $this->object[14]->getType());
    	$this->assertEquals('movie', $this->object[15]->getType());
    	$this->assertEquals('movie', $this->object[16]->getType());
    	$this->assertEquals('movie', $this->object[17]->getType());
    	$this->assertEquals('movie', $this->object[18]->getType());
    	$this->assertEquals('show', $this->object[19]->getType());
    	$this->assertEquals('show', $this->object[20]->getType());
    	$this->assertEquals('show', $this->object[21]->getType());
    	$this->assertEquals('show', $this->object[22]->getType());
    	$this->assertEquals('show', $this->object[23]->getType());
    	$this->assertEquals('show', $this->object[24]->getType());
    	$this->assertEquals('movie', $this->object[26]->getType());
    	$this->assertEquals('movie', $this->object[27]->getType()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
    	$this->assertEquals('movie', $this->object[28]->getType()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS

    }

    public function testGetTitle()
    {
    	$this->assertEquals('Tammy Voll abgefahren', $this->object[0]->getTitle()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
    	$this->assertEquals('22 Jump Street', $this->object[1]->getTitle()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
    	$this->assertEquals('The Purge Anarchy', $this->object[2]->getTitle()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
    	$this->assertEquals('Ein Leben fuer den Tod', $this->object[3]->getTitle()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
    	$this->assertEquals('Mr Peabody And Sherman', $this->object[4]->getTitle()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
    	$this->assertEquals('Angriff der Urzeitmonster', $this->object[5]->getTitle()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
    	$this->assertEquals('Anflug Alpha 1', $this->object[6]->getTitle()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
    	$this->assertEquals('Wer spinnt denn da Herr Doktor', $this->object[7]->getTitle()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
    	$this->assertEquals('The Sugarland Express', $this->object[8]->getTitle()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
    	$this->assertEquals('Hannah Arendt', $this->object[9]->getTitle()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
    	$this->assertEquals('The Rover', $this->object[10]->getTitle()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
    	$this->assertEquals('Transformers Dark Of The Moon', $this->object[11]->getTitle()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
    	$this->assertEquals('Looters Tooters and Sawn Off Shooters', $this->object[12]->getTitle()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
    	$this->assertEquals('The Mask', $this->object[13]->getTitle()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
    	$this->assertEquals('Dumb And Dumber', $this->object[14]->getTitle()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
    	$this->assertEquals('Nurse', $this->object[15]->getTitle()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
    	$this->assertEquals('Free Birds Esst uns an einem anderen Tag', $this->object[16]->getTitle()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
    	$this->assertEquals('Friday The 13th Part III', $this->object[17]->getTitle()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
    	$this->assertEquals('Edge of Tomorrow', $this->object[18]->getTitle()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
    	$this->assertEquals('Rules of Engagement', $this->object[19]->getTitle()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
    	$this->assertEquals('Shortland Street', $this->object[20]->getTitle()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
    	$this->assertEquals('Police Ten 7', $this->object[21]->getTitle()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
    	$this->assertEquals('Die Hoehle der Loewen', $this->object[22]->getTitle()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
    	$this->assertEquals('Supernatural', $this->object[23]->getTitle()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
    	$this->assertEquals('No Foreigners Here 100 Percent British', $this->object[24]->getTitle()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
    	$this->assertEquals('2012', $this->object[26]->getTitle()); //2012.AC3.720p.BluRay.x264-XXL
    	$this->assertEquals('Snowpiercer', $this->object[27]->getTitle()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
    	$this->assertEquals('Noah', $this->object[28]->getTitle()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetResolution()
    {
    	$this->assertEquals('720p', $this->object[0]->getResolution()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
    	$this->assertEquals('1080p', $this->object[1]->getResolution()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
    	$this->assertEquals('1080p', $this->object[2]->getResolution()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
    	$this->assertEquals(NULL, $this->object[3]->getResolution()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
    	$this->assertEquals(NULL, $this->object[4]->getResolution()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
    	$this->assertEquals(NULL, $this->object[5]->getResolution()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
    	$this->assertEquals(NULL, $this->object[6]->getResolution()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
    	$this->assertEquals('1080p', $this->object[7]->getResolution()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
    	$this->assertEquals('1080p', $this->object[8]->getResolution()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
    	$this->assertEquals(NULL, $this->object[9]->getResolution()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
    	$this->assertEquals(NULL, $this->object[10]->getResolution()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
    	$this->assertEquals('1080p', $this->object[11]->getResolution()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
    	$this->assertEquals(NULL, $this->object[12]->getResolution()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
    	$this->assertEquals(NULL, $this->object[13]->getResolution()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
    	$this->assertEquals(NULL, $this->object[14]->getResolution()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
    	$this->assertEquals('720p', $this->object[15]->getResolution()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
    	$this->assertEquals('1080p', $this->object[16]->getResolution()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
    	$this->assertEquals(NULL, $this->object[17]->getResolution()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
    	$this->assertEquals('1080p', $this->object[18]->getResolution()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
    	$this->assertEquals(NULL, $this->object[19]->getResolution()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
    	$this->assertEquals('720p', $this->object[20]->getResolution()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
    	$this->assertEquals('720p', $this->object[21]->getResolution()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
    	$this->assertEquals(NULL, $this->object[22]->getResolution()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
    	$this->assertEquals('720p', $this->object[23]->getResolution()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
    	$this->assertEquals(NULL, $this->object[24]->getResolution()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
    	$this->assertEquals('720p', $this->object[26]->getResolution()); //2012.AC3.720p.BluRay.x264-XXL
    	$this->assertEquals('1080p', $this->object[27]->getResolution()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
    	$this->assertEquals('1080p', $this->object[28]->getResolution()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetSource()
    {
        $this->assertEquals('WebHD', $this->object[0]->getSource()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals('BluRay', $this->object[1]->getSource()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals('BluRay', $this->object[2]->getSource()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals('DVDRip', $this->object[3]->getSource()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals('DVDR', $this->object[4]->getSource()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals('DVDR', $this->object[5]->getSource()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('DVDR', $this->object[6]->getSource()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('BluRay', $this->object[7]->getSource()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals('BluRay', $this->object[8]->getSource()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals('BluRay', $this->object[9]->getSource()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals('BluRay', $this->object[10]->getSource()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals('BluRay', $this->object[11]->getSource()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals('DVDRip', $this->object[12]->getSource()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals('BDRip', $this->object[13]->getSource()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('BDRip', $this->object[14]->getSource()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('BluRay', $this->object[15]->getSource()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals('BluRay', $this->object[16]->getSource()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('BDRip', $this->object[17]->getSource()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals('BluRay', $this->object[18]->getSource()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('DVDRip', $this->object[19]->getSource()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals('HDTV', $this->object[20]->getSource()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals('HDTV', $this->object[21]->getSource()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals('HDTVRip', $this->object[22]->getSource()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals('BluRay', $this->object[23]->getSource()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals('PDTV', $this->object[24]->getSource()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals('BluRay', $this->object[26]->getSource()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals('BluRay', $this->object[27]->getSource()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals('BluRay', $this->object[28]->getSource()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetEncoding()
    {
        $this->assertEquals('h264', $this->object[0]->getEncoding()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals('x264', $this->object[1]->getEncoding()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals('x264', $this->object[2]->getEncoding()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals('XviD', $this->object[3]->getEncoding()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals(NULL, $this->object[4]->getEncoding()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals(NULL, $this->object[5]->getEncoding()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals(NULL, $this->object[6]->getEncoding()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('x264', $this->object[7]->getEncoding()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals('x264', $this->object[8]->getEncoding()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals(NULL, $this->object[9]->getEncoding()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals(NULL, $this->object[10]->getEncoding()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals('x264', $this->object[11]->getEncoding()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals('x264', $this->object[12]->getEncoding()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals('x264', $this->object[13]->getEncoding()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('x264', $this->object[14]->getEncoding()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('x264', $this->object[15]->getEncoding()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals('x264', $this->object[16]->getEncoding()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('x264', $this->object[17]->getEncoding()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals('x264', $this->object[18]->getEncoding()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('x264', $this->object[19]->getEncoding()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals('x264', $this->object[20]->getEncoding()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals('x264', $this->object[21]->getEncoding()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals('x264', $this->object[22]->getEncoding()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals('x264', $this->object[23]->getEncoding()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals('x264', $this->object[24]->getEncoding()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals('x264', $this->object[26]->getEncoding()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals('x264', $this->object[27]->getEncoding()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals('x264', $this->object[28]->getEncoding()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetYear()
    {
        $this->assertEquals(NULL, $this->object[0]->getYear()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals(NULL, $this->object[1]->getYear()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals(NULL, $this->object[2]->getYear()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals('2010', $this->object[3]->getYear()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals('2014', $this->object[4]->getYear()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals('2006', $this->object[5]->getYear()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('1971', $this->object[6]->getYear()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('1982', $this->object[7]->getYear()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals('1974', $this->object[8]->getYear()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals('2012', $this->object[9]->getYear()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals('2014', $this->object[10]->getYear()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals('2011', $this->object[11]->getYear()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals('2014', $this->object[12]->getYear()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals('1994', $this->object[13]->getYear()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('1994', $this->object[14]->getYear()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('2013', $this->object[15]->getYear()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals(NULL, $this->object[16]->getYear()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('1982', $this->object[17]->getYear()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals(NULL, $this->object[18]->getYear()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals(NULL, $this->object[19]->getYear()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals(NULL, $this->object[20]->getYear()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals(NULL, $this->object[21]->getYear()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals(NULL, $this->object[22]->getYear()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals(NULL, $this->object[23]->getYear()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals(NULL, $this->object[24]->getYear()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals(NULL, $this->object[26]->getYear()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals('2013', $this->object[27]->getYear()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals('2014', $this->object[28]->getYear()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetLanguage()
    {
        $this->assertEquals('German', $this->object[0]->getLanguage()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals('German', $this->object[1]->getLanguage()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals('German', $this->object[2]->getLanguage()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals('German', $this->object[3]->getLanguage()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals(NULL, $this->object[4]->getLanguage()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals('German', $this->object[5]->getLanguage()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('German', $this->object[6]->getLanguage()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('German', $this->object[7]->getLanguage()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals('MULTi', $this->object[8]->getLanguage()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals(NULL, $this->object[9]->getLanguage()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals(NULL, $this->object[10]->getLanguage()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals('MULTi', $this->object[11]->getLanguage()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals(NULL, $this->object[12]->getLanguage()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals(NULL, $this->object[13]->getLanguage()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals(NULL, $this->object[14]->getLanguage()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('German', $this->object[15]->getLanguage()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals('German', $this->object[16]->getLanguage()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals(NULL, $this->object[17]->getLanguage()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals('German', $this->object[18]->getLanguage()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('German', $this->object[19]->getLanguage()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals(NULL, $this->object[20]->getLanguage()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals(NULL, $this->object[21]->getLanguage()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals('German', $this->object[22]->getLanguage()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals('German', $this->object[23]->getLanguage()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals(NULL, $this->object[24]->getLanguage()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals(NULL, $this->object[26]->getLanguage()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals('German', $this->object[27]->getLanguage()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals('German', $this->object[28]->getLanguage()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetSeason()
    {
    	  $this->assertEquals(NULL, $this->object[0]->getSeason()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals(NULL, $this->object[1]->getSeason()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals(NULL, $this->object[2]->getSeason()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals(NULL, $this->object[3]->getSeason()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals(NULL, $this->object[4]->getSeason()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals(NULL, $this->object[5]->getSeason()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals(NULL, $this->object[6]->getSeason()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals(NULL, $this->object[7]->getSeason()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals(NULL, $this->object[8]->getSeason()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals(NULL, $this->object[9]->getSeason()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals(NULL, $this->object[10]->getSeason()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals(NULL, $this->object[11]->getSeason()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals(NULL, $this->object[12]->getSeason()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals(NULL, $this->object[13]->getSeason()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals(NULL, $this->object[14]->getSeason()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals(NULL, $this->object[15]->getSeason()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals(NULL, $this->object[16]->getSeason()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals(NULL, $this->object[17]->getSeason()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals(NULL, $this->object[18]->getSeason()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals(5, $this->object[19]->getSeason()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals(23, $this->object[20]->getSeason()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals(21, $this->object[21]->getSeason()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals(1, $this->object[22]->getSeason()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals(9, $this->object[23]->getSeason()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals(1, $this->object[24]->getSeason()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals(NULL, $this->object[26]->getSeason()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals(NULL, $this->object[27]->getSeason()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals(NULL, $this->object[28]->getSeason()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetEpisode()
    {
    	  $this->assertEquals(NULL, $this->object[0]->getEpisode()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals(NULL, $this->object[1]->getEpisode()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals(NULL, $this->object[2]->getEpisode()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals(NULL, $this->object[3]->getEpisode()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals(NULL, $this->object[4]->getEpisode()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals(NULL, $this->object[5]->getEpisode()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals(NULL, $this->object[6]->getEpisode()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals(NULL, $this->object[7]->getEpisode()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals(NULL, $this->object[8]->getEpisode()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals(NULL, $this->object[9]->getEpisode()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals(NULL, $this->object[10]->getEpisode()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals(NULL, $this->object[11]->getEpisode()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals(NULL, $this->object[12]->getEpisode()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals(NULL, $this->object[13]->getEpisode()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals(NULL, $this->object[14]->getEpisode()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals(NULL, $this->object[15]->getEpisode()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals(NULL, $this->object[16]->getEpisode()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals(NULL, $this->object[17]->getEpisode()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals(NULL, $this->object[18]->getEpisode()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals(24, $this->object[19]->getEpisode()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals(180, $this->object[20]->getEpisode()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals(35, $this->object[21]->getEpisode()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals(8, $this->object[22]->getEpisode()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals(8, $this->object[23]->getEpisode()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals(3, $this->object[24]->getEpisode()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals(NULL, $this->object[26]->getEpisode()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals(NULL, $this->object[27]->getEpisode()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals(NULL, $this->object[28]->getEpisode()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetDubbed()
    {
    	  $this->assertEquals('AC3.Dubbed', $this->object[0]->getDubbed()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals('AC3.Dubbed', $this->object[1]->getDubbed()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals('AC3.Dubbed', $this->object[2]->getDubbed()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals('LD', $this->object[3]->getDubbed()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals('', $this->object[4]->getDubbed()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals('', $this->object[5]->getDubbed()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('', $this->object[6]->getDubbed()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('', $this->object[7]->getDubbed()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals('', $this->object[8]->getDubbed()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals('', $this->object[9]->getDubbed()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals('', $this->object[10]->getDubbed()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals('', $this->object[11]->getDubbed()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals('', $this->object[12]->getDubbed()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals('', $this->object[13]->getDubbed()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('', $this->object[14]->getDubbed()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('', $this->object[15]->getDubbed()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals('', $this->object[16]->getDubbed()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('', $this->object[17]->getDubbed()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals('', $this->object[18]->getDubbed()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('', $this->object[19]->getDubbed()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals('', $this->object[20]->getDubbed()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals('', $this->object[21]->getDubbed()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals('', $this->object[22]->getDubbed()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals('DUBBED', $this->object[23]->getDubbed()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals('', $this->object[24]->getDubbed()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals('', $this->object[26]->getDubbed()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals('MD', $this->object[27]->getDubbed()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals('LD', $this->object[28]->getDubbed()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }

    public function testGetGroup()
    {
    	  $this->assertEquals('PsO', $this->object[0]->getGroup()); //Tammy.Voll.abgefahren.German.DL.AC3.Dubbed.720p.WebHD.h264-PsO
        $this->assertEquals('SOV', $this->object[1]->getGroup()); //22.Jump.Street.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-SOV
        $this->assertEquals('Pleaders', $this->object[2]->getGroup()); //The.Purge.Anarchy.German.DL.AC3.Dubbed.1080p.BluRay.x264-Pleaders
        $this->assertEquals('KLASSiGER', $this->object[3]->getGroup()); //Ein.Leben.fuer.den.Tod.German.2010.LD.DVDRip.XviD-KLASSiGER
        $this->assertEquals('JFKDVD', $this->object[4]->getGroup()); //Mr.Peabody.And.Sherman.2014.NTSC.DVDR-JFKDVD
        $this->assertEquals('MOViEiT', $this->object[5]->getGroup()); //Angriff.der.Urzeitmonster.German.2006.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('MOViEiT', $this->object[6]->getGroup()); //Anflug.Alpha.1.German.1971.COMPLETE.PAL.DVDR-MOViEiT
        $this->assertEquals('iFPD', $this->object[7]->getGroup()); //Wer.spinnt.denn.da.Herr.Doktor.1982.German.1080p.BluRay.x264-iFPD
        $this->assertEquals('ULSHD', $this->object[8]->getGroup()); //The.Sugarland.Express.1974.MULTi.1080p.BluRay.x264-ULSHD
        $this->assertEquals('SharpHD', $this->object[9]->getGroup()); //Hannah.Arendt.2012.DUAL.COMPLETE.BLURAY-SharpHD
        $this->assertEquals('XORBiTANT', $this->object[10]->getGroup()); //The.Rover.2014.DUAL.COMPLETE.BLURAY-XORBiTANT
        $this->assertEquals('LUNETTES', $this->object[11]->getGroup()); //Transformers.Dark.Of.The.Moon.2011.3D.MULTi.1080p.BluRay.x264-LUNETTES
        $this->assertEquals('TASTE', $this->object[12]->getGroup()); //Looters.Tooters.and.Sawn.Off.Shooters.2014.DVDRiP.X264-TASTE
        $this->assertEquals('LiBRARiANS', $this->object[13]->getGroup()); //The.Mask.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('LiBRARiANS', $this->object[14]->getGroup()); //Dumb.And.Dumber.1994.iNTERNAL.BDRip.x264-LiBRARiANS
        $this->assertEquals('PussyFoot', $this->object[15]->getGroup()); //Nurse.3D.2013.German.DL.720p.BluRay.x264-PussyFoot
        $this->assertEquals('EXQUiSiTE', $this->object[16]->getGroup()); //Free.Birds.Esst.uns.an.einem.anderen.Tag.3D.HSBS.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('MARS', $this->object[17]->getGroup()); //Friday.The.13th.Part.III.3D.1982.iNTERNAL.BDRip.x264-MARS
        $this->assertEquals('EXQUiSiTE', $this->object[18]->getGroup()); //Edge.of.Tomorrow.3D.HOU.German.DL.1080p.BluRay.x264-EXQUiSiTE
        $this->assertEquals('iNTENTiON', $this->object[19]->getGroup()); //Rules.of.Engagement.S05E24.German.DVDRip.x264-iNTENTiON
        $this->assertEquals('FiHTV', $this->object[20]->getGroup()); //Shortland.Street.S23E180.720p.HDTV.x264-FiHTV
        $this->assertEquals('FiHTV', $this->object[21]->getGroup()); //Police.Ten.7.S21E35.REPACK.720p.HDTV.x264-FiHTV
        $this->assertEquals('SotW', $this->object[22]->getGroup()); //Die.Hoehle.der.Loewen.S01E08.German.HDTVRip.x264-SotW
        $this->assertEquals('TVP', $this->object[23]->getGroup()); //Supernatural.S09E08.Endlich.wieder.Jungfrau.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
        $this->assertEquals('C4TV', $this->object[24]->getGroup()); //No.Foreigners.Here.100.Percent.British.S01E03.PDTV.x264-C4TV
        $this->assertEquals('XXL', $this->object[26]->getGroup()); //2012.AC3.720p.BluRay.x264-XXL
        $this->assertEquals('HuNTER', $this->object[27]->getGroup()); //Snowpiercer.2013.German.AC3.MD.1080p.BluRay.x264-HuNTER
        $this->assertEquals('HCS', $this->object[28]->getGroup()); //Noah.German.2014.LD.1080p.BluRay.x264-HCS
    }
}
